(ns cambrian-collections.main
  (:require
    [cambrian-collections
     [java :as j]
     [vector :as v]
     [map :as m]]))

(def comments
"/**
 *   Copyright (c) Rich Hickey. All rights reserved.
 *   The use and distribution terms for this software are covered by the
 *   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
 *   which can be found in the file epl-v10.html at the root of this distribution.
 *   By using this software in any fashion, you are agreeing to be bound by
 *       the terms of this license.
 *   You must not remove this notice, or any other, from this software.
 **/

// this file is generated by https://github.com/ztellman/cambrian-collections
// do not directly modify

")

(defn -main [& args]
  (spit
    (str "collections/clojure/lang/PersistentUnrolledVector.java")
    (j/format-java
      (str
        comments
        v/class-prelude
        (v/unrolled-vector 6))))

  (spit
    (str "collections/clojure/lang/PersistentUnrolledMap.java")
    (j/format-java
      (str
        comments
        m/class-prelude
        (m/unrolled-map 6)))))
