(ns cambrian-collections.main
  (:require
    [clojure.java.io :refer [make-parents]]
    [cambrian-collections
     [java :as j]
     [vector :as v]
     [map :as m]]))

(def comments
"/**
 *   Copyright (c) Rich Hickey. All rights reserved.
 *   The use and distribution terms for this software are covered by the
 *   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
 *   which can be found in the file epl-v10.html at the root of this distribution.
 *   By using this software in any fashion, you are agreeing to be bound by
 *       the terms of this license.
 *   You must not remove this notice, or any other, from this software.
 **/

// this file is generated by https://github.com/ztellman/cambrian-collections
// do not directly modify

")

(defn gen-java-file [filename prelude code]
  (make-parents filename)
  (spit
    filename
    (j/format-java
      (str
        comments
        prelude
        code))))

(defn -main [& args]
  (gen-java-file
    "collections/clojure/lang/PersistentUnrolledVector.java"
    v/class-prelude
    (v/unrolled-vector 6))

  (gen-java-file
    "collections/clojure/lang/PersistentUnrolledMap.java"
    m/class-prelude
    (m/unrolled-map 6)))
